services:
  - type: web
    name: ai-jewelry-backend
    env: java
    plan: free
    buildCommand: "./mvnw package"  # or just "mvn package" if no wrapper
    startCommand: "java -cp target/ai-jewelry-backend-1.0-SNAPSHOT.jar com.aijewelry.Main"
    envVars:
      - key: JAVA_VERSION
        value: 17
